### ISSUE TITLE
Biome Release Title Changed

### ISSUE THREAD

**Issue by UniquePixels** [Phault/proto-toml-plugins#17]
Biome released 2.0.0 and they changed the format of the release name so the plugin is not finding it.

https://github.com/biomejs/biome/releases/tag/%40biomejs%2Fbiome%402.0.0

**Comment by muuvmuuv** [comment]
Changes:

```toml
version-pattern = "^@biomejs/biome@((?<major>[0-9]+)\\.(?<minor>[0-9]+)\\.(?<patch>[0-9]+)(?<pre>-[^+]+)?)"

download-url = "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%40{version}/{download_file}"
```

You can already use this by using "file://" in your `.prototools` and override the mentioned properties.
